In [ ]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive


## Library

In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, plot_confusion_matrix

## Functions

In [ ]:
def read_data(location):
  vectors_csv = pd.read_csv(location)
  vectors = vectors_csv.to_numpy()
  vectors_data = vectors[:, 1:] # Get the features from the dataset (Read data except labels).
  # vectors_data = np.nan_to_num(vectors_data, nan=0)

  labels = vectors[:, 0].astype(int) # Get labels from the dataset, and convert the type from float to int.
  encoder = OneHotEncoder()
  labels_onehot = encoder.fit_transform(labels.reshape(-1, 1)).toarray()

  return vectors_data, labels_onehot

In [ ]:
def plot_images(vectors, depth, plot_num, image_size=28):
  SIZE = image_size
  vectors_data = vectors
  
  images_data = np.zeros((depth, SIZE, SIZE), dtype=float)
  for k in range(images_data.shape[0]):
    for i in range(SIZE):
      for j in range(SIZE):
        images_data[k, i, j] = vectors_data[k, i * SIZE + j]  # Convert vectors to square matrices.
  
  PLOT_SIZE = plot_num # The number of images to be plotted.

  for i in range(PLOT_SIZE):
    plt.imshow(images_data[i])
    print(labels[i])
    plt.show()

In [7]:
def train(features, labels, model, validation, validation_size, test_size):
  x_train, x_test, y_train, y_test = train_test_split(features, labels, test_size=test_size)
  if validation==1:
    x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=validation_size)
  model.fit(x_train, y_train)
  y_pre = model.predict(x_test)

  acc = accuracy_score(y_test, y_pre)
  print("Accuracy: " + str(acc))
  confusion_matrix(y_test, y_pre)
  plot_confusion_matrix(model, x_test, y_test)

## Execution

In [ ]:
vectors_data, labels = read_data('/drive/My Drive/ML/Project/Numbers.csv')

In [ ]:
print(vectors_data)

[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ... nan nan nan]]


In [ ]:
vectors_data, labels = read_data('/drive/My Drive/ML/Project/Numbers.csv')
# plot_images(vectors_data, vectors_data.shape[0], 20, 28)
model = LogisticRegression(multi_class='ovr')
train(vectors_data, labels, model, validation=0, validation_size=0.2, test_size=0.2)

ValueError: ignored